FROM golang:1.26.6-trixie AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go test ./cmd/kingconsole ./internal/platform ./internal/netguard && \
    CGO_ENABLED=0 go build -trimpath -buildvcs=false -ldflags='-s -w -X main.version=1.3.0' -o /out/kingconsole ./cmd/kingconsole

FROM gcr.io/distroless/static-debian13:nonroot
COPY --from=build /out/kingconsole /usr/local/bin/kingconsole
EXPOSE 18889
ENTRYPOINT ["/usr/local/bin/kingconsole"]
CMD ["-listen","0.0.0.0:18889","-api","http://kingagentd:18888"]
